### ISSUE TITLE
colors.css is overwriting some front-end styles

### ISSUE THREAD

**Issue by eduardozulian** [eduardozulian/admin-bar-color#2]
As reported by @korobochkin, when we enqueue admin styles on the front-end, some overwriting, depending on how the theme was written, can happen. Taking a look at `wp-admin/css/colors/sunrise/colors.css`, for instance, we see:

```css
html {
    background: #f1f1f1;
}

/* Links */
a {
    color: #0074a2;
}

a:hover, a:active, a:focus
{
    color: #0099d5;
}
```
This can set some styles we don't want in our themes.
